run:
  timeout: 5m

issues:
  exclude-dirs:
    - pkg/client
    - vendor
    - "eventsources/common/naivewatcher"
  exclude-files:
    - ".*generated.*"
linters:
  enable:
   # - deadcode # deprecated - replaced by unused
   # - depguard
    - dogsled
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
   # - structcheck # deprecated - replaced by unused
    - typecheck
    - unconvert
    - unused
   # - varcheck # deprecated - replaced by unused
    - whitespace
