name: "Checkout the code of project and the code of E2E from Argo repository"
description: "Checkout the code of the project and the replaces the directory of E2E by the directory from the Argo repository"
inputs:
  project:
    description: 'Project name in the Argo repository'
    required: true
    default: 'argo-events'
  branch:
    description: 'Branch name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout code of Argo
      uses: actions/checkout@v3
      with:
        repository: argoproj/${{ inputs.project }}
        path: argo
        ref: ${{ inputs.branch }}
    - name: Replace test directory by Argo code
      run: cp -r argo/test test
      shell: bash
